version: "3"

services:
  api:
    image: linkextractor-api:step6-ruby
    build: ./api
    ports:
      - "4567:4567"
    environment:
      - REDIS_URL=redis://redis:6379

  web:
    image: linkextractor-web:step6-php
    build: ./www
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://api:4567/api/

  redis:
    image: redis

  locust:
    image: grubykarol/locust
    environment:
      - ATTACKED_HOST=http://web
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/locust
