version: "3"

services:
  api:
    image: linkextractor-api:step4-python
    build: ./api
    ports:
      - "5000:5000"
  web:
    image: php:7-apache
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://api:5000/api/
    volumes:
      - ./www:/var/www/html

  locust:
    image: grubykarol/locust
    environment:
      - ATTACKED_HOST=http://web
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/locust
